version: '3.0'

services:
  jenkins:
    container_name: jenkins
    image: jenkins_chrome_xvfb:lts
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ~/.docker_db_data/jenkins:/var/jenkins_home
