version: '3.0'

services:
  jenkins:
    container_name: jenkins
    image: my_custom_jenkins:lts
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ~/.docker_db_data/jenkins:/var/jenkins_home
